fixtures:
  symlinks:
    threatstack: "#{source_dir}"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    apt: "puppetlabs/apt"
    translate: "puppetlabs/translate"
    auditd: "kemra102/auditd"
    archive: "puppet/archive"
    remote_file: "lwf/remote_file"
