---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: modules
  manifests_path: manifests
  require_chef_for_busser: true
  custom_facts:
    ts_deploy_key: <%= ENV['TS_DEPLOY_KEY'] %>

platforms:
  - name: debian-7.8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    provisioner:
      manifest: site.pp
